### ISSUE TITLE
Add curl to upstream image

### ISSUE THREAD

**Issue by kostajh** [wikimedia/fresh#17]
While trying to run `npm run storybook` in the Popups extension, there is a build step which pulls in external MediaWiki LESS files via curl, and that fails since curl isn't present in the image.

**Comment by kostajh** [comment]
Umm, nevermind, my fork using `podman` had the old image version, I see this has been addressed in 0.6.1

**Comment by Krinkle** [comment]
Last December, for exactly Popups use case in WMF CI, Curl was added to the Docker image that Fresh is based on ([changelog](https://github.com/wikimedia/integration-config/blob/05d4f01c5204b4922dde4c4c5805f9fa44db15c4/dockerfiles/node10-test-browser/changelog#L1-L5)).

This was released as part of Fresh 20.02.1. Does that work for you?

-------

_**EDIT**: I guess it does! 👍_
