### ISSUE TITLE
Promote checksum for install

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/fresh#2]
Per <https://github.com/wikimedia/fresh/pull/1>, we should provide a checksum and recommend it as part of the install command.

Some ideas / questions:
* Hash the bash script during releases and advertise it in the README. Something ubiquitous. Available on Debian/Ubuntu/macOS by default.  `sha1sum`?
* Should we recommend manual post-install inspection?  (install, then `sha1sum /usr/local/bin/fresh-node10` to verify)
* Or provide an automated step as part of the install command?
* Or take apart the install command into three separate steps (e.g. tmp download, verify, chmod+move)

/cc @sbassett29

**Comment by sbassett29** [comment]
I think a manual post-install inspection would probably be the easiest (and simplest) approach for now.
