### ISSUE TITLE
bind source path does not exist: /plain-directory-without-git/.git

### ISSUE THREAD

**Issue by Krinkle** [wikimedia/fresh#3]
```
[23:00 BST] krinkle at KrinkleMac in ~/Documents
$ fresh-node 
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/krinkle/Documents/.git.
See 'docker run --help'.
```

Thanks to @sbassett29 for finding this.

**Comment by sbassett29** [comment]
Simple solution is probably to just wrap an inline conditional around the `--mount` arg at line 89:

`$( if [ -f "$mountsrc/.git" ]; then printf %s "--mount type=bind,source="$mountsrc"/.git,target="$mountdest"/.git,readonly,consistency=cached"; fi ) \`

Though there's also the hard-coded msg at line 80, which may or may not be truthful.
